<a href="https://colab.research.google.com/github/Ajey-Hegde55/Ajey-Hegde55/blob/main/Lab9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Newton's Interpolation Formulae

## 1) Find $y(0.15)$ from the following data:

$x$ $\,$: $\,$ 0.1 $\,$ 0.2 $\,$ 0.3 \\
$y$ $\,$: $\,$ 1 $\,$ 2 $\,$ 3 \\
$i.e.$ \\
$x = [0.1,0.2,0.3] $ \\
$y = [1,2,3]$


In [ ]:
from numpy import*
x=[0.1,0.2,0.3]
y=[1,2,3]
n=len(x)-1
h=x[1]-x[0]
xr=float(input("Enter the value of xr: "))
r=(xr-x[0])/float(h)
Y=y[0]
tem=r
k=1
print("y0 = ",y[0])
print("The forward difference value")
for i in range(0,n):
  y=diff(y)
  print(y)
  Y=Y+tem*y[0]
  tem=tem*(r-k)/(k+1)
  k=k+1
  print(y[0])
print("Interpolated value at %f is %f" %(xr,Y))


Enter the value of xr: 0.15
y0 =  1
The forward difference value
[1 1]
1
[0]
0
Interpolated value at 0.150000 is 1.500000


# 2) Determine the value of $y$ , given $x=51$ from the following data:
\begin{array}{cccccc}x& 50&60&70&80&90\\ y&19.96&36.65&58.81&72.21&94.61\end{array}

In [ ]:
from numpy import*
x=[50,60,70,80,90]
y=[19.96,36.65,58.81,72.21,94.61]
n=len(x)-1
h=x[1]-x[0]
xr=float(input("Enter the value of xr: "))
r=(xr-x[0])/float(h)
Y=y[0]
tem=r
k=1
print("y0 = ",y[0])
print("The forward difference value")
for i in range(0,n):
  y=diff(y)
  print(y)
  Y=Y+tem*y[0]
  tem=tem*(r-k)/(k+1)
  k=k+1
  print(y[0])
print("Interpolated value at %f is %f" %(xr,Y))


Enter the value of xr: 51
y0 =  19.96
The forward difference value
[16.69 22.16 13.4  22.4 ]
16.689999999999998
[ 5.47 -8.76  9.  ]
5.470000000000006
[-14.23  17.76]
-14.230000000000018
[31.99]
31.990000000000045
Interpolated value at 51.000000 is 20.316302


## 3) Given $f(40)=184$, $f(50)=204$, $f(60)=226$, $f(70)=250$, $f(80)=276$ and $f(90)=304$, find $f(85)$ using suitable interpolation formula.

In [ ]:
from numpy import*
x=[40,50,60,70,80,90]
y=[184,204,226,250,276,304]
n=len(x)-1
h=x[1]-x[0]
xq=float(input("Enter the value of xq: "))
q=(xq-x[n])/float(h)
Y=y[n]
tem=q
k=1
print("yn = ",y[n])
print("The backward difference value")
for i in range(0,n):
  y=diff(y)
  print(y)
  Y=Y+tem*y[-1]
  tem=tem*(q+k)/(k+1)
  k=k+1
  print(y[-1])
print("Interpolated value at %f is %f" %(xq,Y))


Enter the value of xq: 85
yn =  304
The backward difference value
[20 22 24 26 28]
28
[2 2 2 2]
2
[0 0 0]
0
[0 0]
0
[0]
0
Interpolated value at 85.000000 is 289.750000


## 4) The area of a a circle (A) corresponding to diameter (D) is given below:
## D = [80,85,90,95,100]
## A = [5026,5674,6362,7088,7854]
## Find the area corresponding to the diameter 105 using an appropriate interpolation formula.

In [ ]:
from numpy import*
x = [80,85,90,95,100]
y = [5026,5674,6362,7088,7854]
n=len(x)-1
h=x[1]-x[0]
xq=float(input("Enter the value of xq: "))
q=(xq-x[n])/float(h)
Y=y[n]
tem=q
k=1
print("yn = ",y[n])
print("The backward difference value")
for i in range(0,n):
  y=diff(y)
  print(y)
  Y=Y+tem*y[-1]
  tem=tem*(q+k)/(k+1)
  k=k+1
  print(y[-1])
print("Interpolated value at %f is %f" %(xq,Y))
print("Therefore, the area corresponding to the diameter 105 is: ",Y)

Enter the value of xq: 105
yn =  7854
The backward difference value
[648 688 726 766]
766
[40 38 40]
40
[-2  2]
2
[4]
4
Interpolated value at 105.000000 is 8666.000000
Therefore, the area corresponding to the diameter 105 is:  8666.0


## Numerical integration

## 1) Using Simpson's $1/3^{rd}$ rule, evaluate $\int_0^\pi\sin{x}dx$.





In [ ]:
from numpy import*
a=float(input("Enter the lower limit: "))
b=float(input("Enter the upper limit: "))
n=(int(input("Enter an even number for the number of subintervals: ")))
h=(b-a)/n
x=linspace(a,b,n+1)
f=sin(x)
Sum=0
for i in range(1,n+1):
  if i%2==0:
    Sum=Sum+2*f[i]
  else:
    Sum=Sum+4*f[i]
I=(h/3)*(f[0]+Sum+f[n])
print("The value of the integral is %0.5f "%I)

Enter the lower limit: 0
Enter the upper limit: 3.14159
Enter an even number for the number of subintervals: 26
The value of the integral is 2.00000 


## 2) Using Simpson's $3/8^{th}$ rule, evaluate $\int_0^\pi\sin{x}dx$.

In [ ]:
from numpy import*
a=float(input("Enter the lower limit: "))
b=float(input("Enter the upper limit: "))
n=(int(input("Enter the number of subintervals(multiple of 3): ")))
h=(b-a)/n
x=linspace(a,b,n+1)
f=sin(x)
Sum=0
for i in range(1,n+1):
  if i%3==0:
    Sum=Sum+2*f[i]
  else:
    Sum=Sum+3*f[i]
I=(3*h/8)*(f[0]+Sum+f[n])
print("The value of the integral is %0.5f "%I)

Enter the lower limit: 0
Enter the upper limit: 3.14159
Enter the number of subintervals(multiple of 3): 21
The value of the integral is 2.00001 


## 3) Using Simpson's $1/3^{rd}$ rule, evaluate $\int_0^{0.6}e^{-x^2}dx$.

In [ ]:
from numpy import*
a=float(input("Enter the lower limit: "))
b=float(input("Enter the upper limit: "))
n=(int(input("Enter an even number for the number of subintervals: ")))
h=(b-a)/n
x=linspace(a,b,n+1)
f=exp(-x**2)
Sum=0
for i in range(1,n+1):
  if i%2==0:
    Sum=Sum+2*f[i]
  else:
    Sum=Sum+4*f[i]
I=(h/3)*(f[0]+Sum+f[n])
print("The value of the integral is %0.5f "%I)

Enter the lower limit: 0
Enter the upper limit: .6
Enter an even number for the number of subintervals: 10
The value of the integral is 0.56306 


## 4) Using Simpson's $3/8^{th}$ rule, evaluate $\int_4^{5.2}log(x)dx$.

In [ ]:
from numpy import*
a=float(input("Enter the lower limit: "))
b=float(input("Enter the upper limit: "))
n=(int(input("Enter the number of subintervals(multiple of 3): ")))
h=(b-a)/n
x=linspace(a,b,n+1)
f=log(x)
Sum=0
for i in range(1,n+1):
  if i%3==0:
    Sum=Sum+2*f[i]
  else:
    Sum=Sum+3*f[i]
I=(3*h/8)*(f[0]+Sum+f[n])
print("The value of the integral is %0.5f "%I)

Enter the lower limit: 4
Enter the upper limit: 5.2
Enter the number of subintervals(multiple of 3): 12
The value of the integral is 1.95150 
